### ISSUE TITLE
To-do before CRAN submission

### ISSUE THREAD

**Issue by matcasti** [matcasti/kinemov#1]
## Before CRAN

Here is a list with modifications and improvements that need to be made before submitting to CRAN:

- [ ] Add an article explaining the logic under angle measurement between adyacent joints.
- [ ] Add an article into creating a simple-to-make 2D motion capture using ImageJ and MTrackJ.

## Ideas still under consideration

- [ ] Add a suite of functions to analyze EMG?
